### ISSUE TITLE
About the model

### ISSUE THREAD

**Issue by timqian** [tartavull/snn-rl#10]
Thanks for opensourcing your work here. I am new to SNN and willing to learn more about it. Your paper and code helped me a lot. And I have some questions about your model.

In my opinion, STDP rule and Lateral inhibition is used for picking up successful patterns. And because the initial weights between neurons are generated randomly, I think it is possible that some times different patterns will have same output.

For example, a simple network only have two inputs and two outputs, The purpose of the net is to distinguish two types of inputs, [1, 0] and [0, 1]. We hope different output neuron will fire according to different inputs. The structure is shown in the picture:

![img_20151124_133718](https://cloud.githubusercontent.com/assets/5512552/11358781/ce1ddc94-92b0-11e5-9d44-8b2283141682.jpg)

The problem is: because the weights are generated randomly, the weights shown in the picture is possible to occur. When the weights are like this, I think after training, the two kinds of inputs will generate the same output [0, 1].

Is this really a problem, or I am wrong in some place? If this is a problem, how did you solve it.
thank you

**Comment by nmsutton** [comment]
Thanks for bringing up this question.  I would have to consider your question more to provide a more thought through answer but in first impression I will share some ideas that possibly could help answer it if I understand right.  

From what I recall there was an issue where randomized weights can as you say generate the same output because they were randomly both closer to that output neuron's activation.  In my opinion calling this a problem may be a misconception depending on one's purposes.  The process of randomization avoids producing a predetermined result, in that way also it helps avoid overtraining.  It can potentially be considered an advantage that the model does not learn exactly the correct output to avoid that.

On the other hand, naturally in many models one would want to have it generate the specific results output based on inputs with high accuracy.  In the original paper this project was modeled after some parameters were set as fixed such as randomization but for the interest of exploring ways to avoid an issue such as the one you pointed out and tune the code to produce higher accuracy results in the latest version of the project I implemented parameter optimization of initial randomization, reinforcement strengths, and others.  That is included in /optSim.py and results are described in http://nbviewer.ipython.org/github/tartavull/snn-rl/blob/master/FFSSN.ipynb.

Does that answer the question or were there some parts I should address more?

**Comment by timqian** [comment]
Thank you for your reply, @nmsutton, I will carefully read your materials first.

**Comment by nmsutton** [comment]
You're welcome @timqlan, further questions are welcome if they come up.

**Comment by nmsutton** [comment]
Closing this issue due to questions having been answered. Thanks @timqian for your descriptions of considerations of the experiments which can help users think about and understand them in different ways.
