### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'times'

### ISSUE THREAD

**Issue by assadRasheed** [tartavull/snn-rl#12]
why this error is showing .i am unable to solve this....
TypeError                                 Traceback (most recent call last)
<ipython-input-1-b2ca72dcf31d> in <module>()
      3 dictionary = dictionary()
      4 spiketimes = dictionary.spikeTimes(dictionaryLongitude, spikeInterval, spikesPerChar, epochs)
----> 5 LIK = SpikeGeneratorGroup(15, spiketimes)
      6 
      7 eqs = Equations('''

~\Anaconda3.0\lib\site-packages\brian2\units\fundamentalunits.py in new_f(*args, **kwds)
   2358                                                      get_dimensions(newkeyset[k]))
   2359 
-> 2360             result = f(*args, **kwds)
   2361             if 'result' in au:
   2362                 if au['result'] == bool:

TypeError: __init__() missing 1 required positional argument: 'times'

**Comment by nmsutton** [comment]
@assadRasheed I have not been able to recreate this error but I have been able to do a fresh install of anaconda and run the software successfully after updating the dictionary.py file as detailed in my response to your other issue post. One difference is that I see you are using anaconda 3.0 and I used version 2.5 for my test. Other than that, please provide details about what system are you using that the error occurred on? Also, if you use the new dictionary.py file I uploaded does it somehow fix this issue as well?

For comparison, I tested this with a clean install of anaconda 2.5.0 (haven’t tested the latest anaconda) on Ubuntu 16.04.1 LTS and installing brian2 (2.0.2.1) through instuctions similar to [these](https://anaconda.org/brian-team/brian2). All my python packages were installed though ‘conda install ...’. I needed numpy, scipy, and matplotlib to allow the software to work. Since the error is a brian2 one, try updating brian2 to the newest version (if needed ‘conda install -c brian-team brian2=2.0.2.1’). If you are continuing to have the error is it possible for you to test on your machine a similar enviornment to the one I am describing and see if you get the error in that case?

**Comment by nmsutton** [comment]
Closing this issue because fixes have been added and software is running successfully. @assadRasheed thank you for reporting the issue. Glad to now avoid users having this come up thanks to your reporting of it which allowed it to be fixed.
