### ISSUE TITLE
No module named report_results_and_logging

### ISSUE THREAD

**Issue by timqian** [tartavull/snn-rl#9]
While running `originalVersion/gupta_paper.py `, this err showed up.
And I can not find this module anywhere in the project.

**Comment by nmsutton** [comment]
Hi, thanks for reporting this and glad to see your interest in the project.  Looks like that file was lost when I reorganized the file structure.  I have tried to find the most resent version of that file and have uploaded it to the directory.  Please tell me does it work now?  I have brian2 installed instead of brian so I haven't confirmed it working yet.  

I can see how sequentially starting with the older version of the project to understand it then looking at the newer one can help but in case of confusion the latest version of the project is contained in the /gupta_paper_further_formulas.py file.  Is it a little confusing in the project description that is the case?

**Comment by timqian** [comment]
Thanks @nmsutton , it works now, 
and your description is fine, I just want to try the simple version first.
